### ISSUE TITLE
Create Design templates on figma  

### ISSUE THREAD

**Issue by Zain-ul-din** [Zain-ul-din/LGU-TimetableV2#2]
### TODOS

- [ ] Light/Dark color palate.
- [ ] Sticky Nav-Bar on the Left side.
- [ ] drop-down input component.
- [ ] Responsive tables for timetable.
- [ ] Date Input component.
- [ ] Free classrooms list.
- [ ] Footer & about us.
- [ ] hall of fame for collaborators.
- [ ] Responsive design for mobile devices.

Prefer Theme: Light theme (Light Blue)/ Dark theme (dark gray).

### <a href='https://www.figma.com/file/U9iYVbiOIp5TUYvEGI9V6S/LGU-TimetableApp?node-id=0%3A1&t=gvaelVBDR3Q16teF-1'>Get Started From Here.</a>

Share your Figma design templates <a href='https://github.com/Zain-ul-din/LGU-TimetableV2/discussions/categories/ideas'>here</a>.
